---- CREATE DATABASE ----
-- CREATE DATABASE YashGotechaDB;


---- CREATE TABLE ----
-- CREATE TABLE CUSTOMERS(
--    ID   INT              NOT NULL,
--    NAME VARCHAR (20)     NOT NULL,
--    AGE  INT              NOT NULL,
--    ADDRESS  CHAR (25) ,
--    SALARY   DECIMAL (18, 2),       
--    PRIMARY KEY (ID)
-- );
-- CREATE TABLE ORDERS (
--    OID     INT              NOT NULL,
--    DATE date     NOT NULL,
--    CUSTOMER_ID  INT              NOT NULL,
--    AMOUNT   DECIMAL (18, 2),       
--    PRIMARY KEY (OID)
-- );



----INSERT Query----
-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

-- INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
-- VALUES (6, 'Komal', 22, 'MP', 4500.00 );

-- INSERT INTO CUSTOMERS 
-- VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );

-- INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
-- VALUES (102 , '2009-10-08 00:00:00', 3, 3000 );

-- INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
-- VALUES (100  , '2009-10-08 00:00:00', 3, 1500 );

-- INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
-- VALUES (101 , '2009-11-08 00:00:00', 3, 1560 );

-- INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
-- VALUES (103 , '2008-05-08 00:00:00', 3, 2060 );


----SELECT Query----
 --SELECT * FROM CUSTOMERS;

 --SELECT ID, NAME, SALARY FROM CUSTOMERS;


----WHERE Clause----
-- SELECT ID, NAME, SALARY 
-- FROM CUSTOMERS
-- WHERE SALARY > 2000;

-- SELECT ID, NAME, SALARY 
-- FROM CUSTOMERS
-- WHERE NAME = 'Hardik';


----AND and OR Conjunctive Operators----
-- SELECT ID, NAME, SALARY 
-- FROM CUSTOMERS
-- WHERE SALARY > 2000 AND age < 25;

-- SELECT ID, NAME, SALARY 
-- FROM CUSTOMERS
-- WHERE SALARY > 2000 OR age < 25;


----UPDATE Query----
-- UPDATE CUSTOMERS
-- SET ADDRESS = 'Pune'
-- WHERE ID = 6;

-- UPDATE CUSTOMERS
-- SET ADDRESS = 'MP'
-- WHERE ID = 6;


----DELETE Query----
-- DELETE FROM CUSTOMERS
-- WHERE ID = 6;


----LIKE Clause----
-- SELECT * FROM CUSTOMERS
-- WHERE SALARY LIKE '200%';


----TOP Clause----
-- SELECT TOP 3 * FROM CUSTOMERS;


----ORDER BY Clause----
-- SELECT * FROM CUSTOMERS
-- ORDER BY NAME, SALARY;

-- SELECT * FROM CUSTOMERS
-- ORDER BY NAME DESC;


----Group By----
-- SELECT NAME, SUM(SALARY) FROM CUSTOMERS
-- GROUP BY NAME;


----Distinct Keyword----
-- SELECT DISTINCT SALARY FROM CUSTOMERS
-- ORDER BY SALARY;


----Using Joins----
-- SELECT  ID, NAME, AMOUNT, DATE
-- FROM CUSTOMERS
-- INNER JOIN ORDERS
-- ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--SELECT  ID, NAME, AMOUNT, DATE
--FROM CUSTOMERS
--LEFT JOIN ORDERS
--ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--SELECT  ID, NAME, AMOUNT, DATE
--FROM CUSTOMERS
--RIGHT JOIN ORDERS
--ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--SELECT  ID, NAME, AMOUNT, DATE
--FROM CUSTOMERS
--FULL JOIN ORDERS
--ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;


--EXEC innerJoin;



